dist: trusty
sudo: required
language: node_js
os:
  - osx
node_js:
  - "6"
  - "5"
  - "4"
before_script:
  - npm install .
env:
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
"scripts": {
  "test": "./node_modules/mocha/bin/mocha test/all.js"
}


